// Vulkan MoE Expert Cache.
//
// Keeps the hottest CPU-resident MoE expert weights resident in VRAM so
// decode-time expert matvecs run on the GPU instead of the CPU path.
//
// This implements the real ggml_moe_cache_api contract (see
// ggml-backend-moe-cache.h). The scheduler owns one cache session; the
// CPU MUL_MAT_ID path calls begin/plan/dispatch/collect/end per node.
//
// v1 notes:
//   - synchronous fills (no worker thread): plan() copies missed experts
//     into the slab before returning and serves them in this node
//   - fills per plan are bounded by inserts_per_plan (and queue_mb)
//   - one pool per (expert_size, wtype), allocated lazily in begin()
//   - UMA devices (memory type DEVICE_LOCAL|HOST_VISIBLE) use direct
//     host-mapped slabs; discrete GPUs use DEVICE_LOCAL + staging copies
//   - fused SwiGLU returns NULL (stock CPU path handles the node)
//
// Register by calling ggml_vulkan_moe_cache_register() from
// ggml_backend_vk_reg() after the backend reg struct is set up.

#include <vulkan/vulkan.h>

#include "ggml-vulkan.h"

#include "ggml-backend-impl.h"
#include "ggml-backend.h"
#include "ggml-impl.h"
#include "ggml.h"
#include "../ggml-quants.h"
#include "../ggml-moe-cache-common.h"

#include <cstring>
#include <mutex>
#include <unordered_set>
#include <vector>

// Generated by vulkan-shaders-gen from vulkan-shaders/moe_cache_mv.comp.
// One variant per weight type (see process_shaders()).
#include "ggml-vulkan-shaders.hpp"

extern const uint64_t moe_cache_mv_q8_0_len;
extern const unsigned char moe_cache_mv_q8_0_data[];
extern const uint64_t moe_cache_mv_q4_0_len;
extern const unsigned char moe_cache_mv_q4_0_data[];
extern const uint64_t moe_cache_mv_q4_K_len;
extern const unsigned char moe_cache_mv_q4_K_data[];
extern const uint64_t moe_cache_mv_q6_K_len;
extern const unsigned char moe_cache_mv_q6_K_data[];
extern const uint64_t moe_cache_mv_q5_K_len;
extern const unsigned char moe_cache_mv_q5_K_data[];
extern const uint64_t moe_cache_mv_q1_0_len;
extern const unsigned char moe_cache_mv_q1_0_data[];
extern const uint64_t moe_cache_mv_q2_0_len;
extern const unsigned char moe_cache_mv_q2_0_data[];
extern const uint64_t moe_cache_mv_q4_1_len;
extern const unsigned char moe_cache_mv_q4_1_data[];
extern const uint64_t moe_cache_mv_q5_0_len;
extern const unsigned char moe_cache_mv_q5_0_data[];
extern const uint64_t moe_cache_mv_q5_1_len;
extern const unsigned char moe_cache_mv_q5_1_data[];
extern const uint64_t moe_cache_mv_q2_K_len;
extern const unsigned char moe_cache_mv_q2_K_data[];
extern const uint64_t moe_cache_mv_q3_K_len;
extern const unsigned char moe_cache_mv_q3_K_data[];
extern const uint64_t moe_cache_mv_iq2_xxs_len;
extern const unsigned char moe_cache_mv_iq2_xxs_data[];
extern const uint64_t moe_cache_mv_iq2_xs_len;
extern const unsigned char moe_cache_mv_iq2_xs_data[];
extern const uint64_t moe_cache_mv_iq2_s_len;
extern const unsigned char moe_cache_mv_iq2_s_data[];
extern const uint64_t moe_cache_mv_iq3_xxs_len;
extern const unsigned char moe_cache_mv_iq3_xxs_data[];
extern const uint64_t moe_cache_mv_iq3_s_len;
extern const unsigned char moe_cache_mv_iq3_s_data[];
extern const uint64_t moe_cache_mv_iq1_s_len;
extern const unsigned char moe_cache_mv_iq1_s_data[];
extern const uint64_t moe_cache_mv_iq1_m_len;
extern const unsigned char moe_cache_mv_iq1_m_data[];
extern const uint64_t moe_cache_mv_iq4_nl_len;
extern const unsigned char moe_cache_mv_iq4_nl_data[];
extern const uint64_t moe_cache_mv_iq4_xs_len;
extern const unsigned char moe_cache_mv_iq4_xs_data[];
extern const uint64_t moe_cache_mv_mxfp4_len;
extern const unsigned char moe_cache_mv_mxfp4_data[];
extern const uint64_t moe_cache_mv_nvfp4_len;
extern const unsigned char moe_cache_mv_nvfp4_data[];

// Thread-local session stack (owned by this backend; independent of CUDA's).
static thread_local std::vector<moe_cache_scope_frame> g_session_stack;
static thread_local int g_session_suppressed = 0;

// Global session registry for invalidate()/teardown paths.
static std::mutex g_registry_mu;
static std::unordered_set<moe_cache_session *> g_sessions;
// Live-session count, so invalidate() can bail before taking g_registry_mu.
// invalidate runs on every backend buffer write; with no cache active that was
// one mutex acquire per write during model load.
static std::atomic<size_t> g_session_count{0};

// Backend registration object this provider was registered under.
static const void * g_moe_cache_owner = nullptr;

// ---------------------------------------------------------------------------
// Vulkan device extension
// ---------------------------------------------------------------------------

struct vk_buf {
    VkBuffer buffer = VK_NULL_HANDLE;
    VkDeviceMemory memory = VK_NULL_HANDLE;
    VkDeviceSize size = 0;
    void * mapped = nullptr; // valid when host-visible
    bool host_visible = false;
};

struct moe_cache_vulkan_device : public moe_cache_device {
    moe_cache_vulkan_device(int logical, int physical)
        : moe_cache_device(logical, physical) {}

    ~moe_cache_vulkan_device() { free_resources(); }

    VkDevice vk_device = VK_NULL_HANDLE;
    VkPhysicalDevice vk_physical = VK_NULL_HANDLE;
    VkQueue vk_queue = VK_NULL_HANDLE;
    uint32_t vk_queue_family = 0;
    VkCommandPool vk_cmd_pool = VK_NULL_HANDLE;

    // true when a DEVICE_LOCAL|HOST_VISIBLE memory type exists (UMA).
    bool host_mapped = false;

    // Command pool and pipelines are created lazily on the first begin, so a
    // context that never uses the cache allocates no GPU objects.
    std::once_flag init_once;
    bool init_ok = false;

    // pipelines, one per supported weight type
    VkPipeline pipeline_q8_0 = VK_NULL_HANDLE;
    VkPipeline pipeline_q4_0 = VK_NULL_HANDLE;
    VkPipeline pipeline_q4_K = VK_NULL_HANDLE;
    VkPipeline pipeline_q6_K = VK_NULL_HANDLE;
    VkPipeline pipeline_q5_K = VK_NULL_HANDLE;
    VkPipeline pipeline_q1_0 = VK_NULL_HANDLE;
    VkPipeline pipeline_q2_0 = VK_NULL_HANDLE;
    VkPipeline pipeline_q4_1 = VK_NULL_HANDLE;
    VkPipeline pipeline_q5_0 = VK_NULL_HANDLE;
    VkPipeline pipeline_q5_1 = VK_NULL_HANDLE;
    VkPipeline pipeline_q2_K = VK_NULL_HANDLE;
    VkPipeline pipeline_q3_K = VK_NULL_HANDLE;
    VkPipeline pipeline_iq2_xxs = VK_NULL_HANDLE;
    VkPipeline pipeline_iq2_xs = VK_NULL_HANDLE;
    VkPipeline pipeline_iq2_s = VK_NULL_HANDLE;
    VkPipeline pipeline_iq3_xxs = VK_NULL_HANDLE;
    VkPipeline pipeline_iq3_s = VK_NULL_HANDLE;
    VkPipeline pipeline_iq1_s = VK_NULL_HANDLE;
    VkPipeline pipeline_iq1_m = VK_NULL_HANDLE;
    VkPipeline pipeline_iq4_nl = VK_NULL_HANDLE;
    VkPipeline pipeline_iq4_xs = VK_NULL_HANDLE;
    VkPipeline pipeline_mxfp4 = VK_NULL_HANDLE;
    VkPipeline pipeline_nvfp4 = VK_NULL_HANDLE;
    VkPipelineLayout pipeline_layout = VK_NULL_HANDLE;
    VkDescriptorSetLayout ds_layout = VK_NULL_HANDLE;
    VkDescriptorPool ds_pool = VK_NULL_HANDLE;
    VkDescriptorSet ds = VK_NULL_HANDLE;

    // slab buffer per pool (parallel to pools)
    std::vector<vk_buf> pool_buffers;

    // scratch buffers
    vk_buf ids_buf;
    vk_buf act_buf;
    vk_buf out_buf;
    vk_buf params_buf;
    vk_buf staging;      // host-visible, transfer src+dst
    std::vector<float> h_act; // host scratch for quantized activations
    size_t h_act_cap_bytes = 0;

    void free_resources() {
        for (auto & buf : pool_buffers) {
            destroy_buf(buf);
        }
        pool_buffers.clear();
        destroy_buf(ids_buf);
        destroy_buf(act_buf);
        destroy_buf(out_buf);
        destroy_buf(params_buf);
        destroy_buf(staging);

        if (ds_pool) {
            vkDestroyDescriptorPool(vk_device, ds_pool, nullptr);
            ds_pool = VK_NULL_HANDLE;
        }
        if (ds_layout) {
            vkDestroyDescriptorSetLayout(vk_device, ds_layout, nullptr);
            ds_layout = VK_NULL_HANDLE;
        }
        if (pipeline_layout) {
            vkDestroyPipelineLayout(vk_device, pipeline_layout, nullptr);
            pipeline_layout = VK_NULL_HANDLE;
        }
        if (pipeline_q8_0) { vkDestroyPipeline(vk_device, pipeline_q8_0, nullptr); pipeline_q8_0 = VK_NULL_HANDLE; }
        if (pipeline_q4_0) { vkDestroyPipeline(vk_device, pipeline_q4_0, nullptr); pipeline_q4_0 = VK_NULL_HANDLE; }
        if (pipeline_q4_K) { vkDestroyPipeline(vk_device, pipeline_q4_K, nullptr); pipeline_q4_K = VK_NULL_HANDLE; }
        if (pipeline_q6_K) { vkDestroyPipeline(vk_device, pipeline_q6_K, nullptr); pipeline_q6_K = VK_NULL_HANDLE; }
        if (pipeline_q5_K) { vkDestroyPipeline(vk_device, pipeline_q5_K, nullptr); pipeline_q5_K = VK_NULL_HANDLE; }
        if (pipeline_q1_0) { vkDestroyPipeline(vk_device, pipeline_q1_0, nullptr); pipeline_q1_0 = VK_NULL_HANDLE; }
        if (pipeline_q2_0) { vkDestroyPipeline(vk_device, pipeline_q2_0, nullptr); pipeline_q2_0 = VK_NULL_HANDLE; }
        if (pipeline_q4_1) { vkDestroyPipeline(vk_device, pipeline_q4_1, nullptr); pipeline_q4_1 = VK_NULL_HANDLE; }
        if (pipeline_q5_0) { vkDestroyPipeline(vk_device, pipeline_q5_0, nullptr); pipeline_q5_0 = VK_NULL_HANDLE; }
        if (pipeline_q5_1) { vkDestroyPipeline(vk_device, pipeline_q5_1, nullptr); pipeline_q5_1 = VK_NULL_HANDLE; }
        if (pipeline_q2_K) { vkDestroyPipeline(vk_device, pipeline_q2_K, nullptr); pipeline_q2_K = VK_NULL_HANDLE; }
        if (pipeline_q3_K) { vkDestroyPipeline(vk_device, pipeline_q3_K, nullptr); pipeline_q3_K = VK_NULL_HANDLE; }
        if (pipeline_iq2_xxs) { vkDestroyPipeline(vk_device, pipeline_iq2_xxs, nullptr); pipeline_iq2_xxs = VK_NULL_HANDLE; }
        if (pipeline_iq2_xs) { vkDestroyPipeline(vk_device, pipeline_iq2_xs, nullptr); pipeline_iq2_xs = VK_NULL_HANDLE; }
        if (pipeline_iq2_s) { vkDestroyPipeline(vk_device, pipeline_iq2_s, nullptr); pipeline_iq2_s = VK_NULL_HANDLE; }
        if (pipeline_iq3_xxs) { vkDestroyPipeline(vk_device, pipeline_iq3_xxs, nullptr); pipeline_iq3_xxs = VK_NULL_HANDLE; }
        if (pipeline_iq3_s) { vkDestroyPipeline(vk_device, pipeline_iq3_s, nullptr); pipeline_iq3_s = VK_NULL_HANDLE; }
        if (pipeline_iq1_s) { vkDestroyPipeline(vk_device, pipeline_iq1_s, nullptr); pipeline_iq1_s = VK_NULL_HANDLE; }
        if (pipeline_iq1_m) { vkDestroyPipeline(vk_device, pipeline_iq1_m, nullptr); pipeline_iq1_m = VK_NULL_HANDLE; }
        if (pipeline_iq4_nl) { vkDestroyPipeline(vk_device, pipeline_iq4_nl, nullptr); pipeline_iq4_nl = VK_NULL_HANDLE; }
        if (pipeline_iq4_xs) { vkDestroyPipeline(vk_device, pipeline_iq4_xs, nullptr); pipeline_iq4_xs = VK_NULL_HANDLE; }
        if (pipeline_mxfp4) { vkDestroyPipeline(vk_device, pipeline_mxfp4, nullptr); pipeline_mxfp4 = VK_NULL_HANDLE; }
        if (pipeline_nvfp4) { vkDestroyPipeline(vk_device, pipeline_nvfp4, nullptr); pipeline_nvfp4 = VK_NULL_HANDLE; }
        if (vk_cmd_pool) {
            vkDestroyCommandPool(vk_device, vk_cmd_pool, nullptr);
            vk_cmd_pool = VK_NULL_HANDLE;
        }
        for (auto & pool : pools) {
            pool->slab = nullptr;
        }
    }

private:
    void destroy_buf(vk_buf & buf) {
        if (buf.buffer) {
            vkDestroyBuffer(vk_device, buf.buffer, nullptr);
            buf.buffer = VK_NULL_HANDLE;
        }
        if (buf.memory) {
            vkFreeMemory(vk_device, buf.memory, nullptr);
            buf.memory = VK_NULL_HANDLE;
        }
        buf.mapped = nullptr;
        buf.size = 0;
        buf.host_visible = false;
    }
};

// ---------------------------------------------------------------------------
// Buffer helpers
// ---------------------------------------------------------------------------

static uint32_t vk_find_mem_type(VkPhysicalDevice phys, uint32_t type_filter,
                                 VkMemoryPropertyFlags props) {
    VkPhysicalDeviceMemoryProperties mem_props;
    vkGetPhysicalDeviceMemoryProperties(phys, &mem_props);
    for (uint32_t i = 0; i < mem_props.memoryTypeCount; i++) {
        if ((type_filter & (1u << i)) &&
            (mem_props.memoryTypes[i].propertyFlags & props) == props) {
            return i;
        }
    }
    return UINT32_MAX;
}

static bool vk_buf_create(moe_cache_vulkan_device & dev, VkDeviceSize size,
                          VkBufferUsageFlags usage, VkMemoryPropertyFlags props,
                          vk_buf & out) {
    VkBufferCreateInfo bci = {};
    bci.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
    bci.size = size;
    bci.usage = usage;
    bci.sharingMode = VK_SHARING_MODE_EXCLUSIVE;

    if (vkCreateBuffer(dev.vk_device, &bci, nullptr, &out.buffer) != VK_SUCCESS) {
        return false;
    }

    VkMemoryRequirements mem_req;
    vkGetBufferMemoryRequirements(dev.vk_device, out.buffer, &mem_req);

    const uint32_t type_index =
        vk_find_mem_type(dev.vk_physical, mem_req.memoryTypeBits, props);
    if (type_index == UINT32_MAX) {
        vkDestroyBuffer(dev.vk_device, out.buffer, nullptr);
        out.buffer = VK_NULL_HANDLE;
        return false;
    }

    VkMemoryAllocateInfo mai = {};
    mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    mai.allocationSize = mem_req.size;
    mai.memoryTypeIndex = type_index;

    if (vkAllocateMemory(dev.vk_device, &mai, nullptr, &out.memory) != VK_SUCCESS) {
        vkDestroyBuffer(dev.vk_device, out.buffer, nullptr);
        out.buffer = VK_NULL_HANDLE;
        return false;
    }

    if (vkBindBufferMemory(dev.vk_device, out.buffer, out.memory, 0) != VK_SUCCESS) {
        vkFreeMemory(dev.vk_device, out.memory, nullptr);
        out.memory = VK_NULL_HANDLE;
        vkDestroyBuffer(dev.vk_device, out.buffer, nullptr);
        out.buffer = VK_NULL_HANDLE;
        return false;
    }

    out.size = size;
    out.host_visible = (props & VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT) != 0;
    if (out.host_visible) {
        vkMapMemory(dev.vk_device, out.memory, 0, size, 0, &out.mapped);
    }
    return true;
}

static void vk_buf_destroy(moe_cache_vulkan_device & dev, vk_buf & buf) {
    if (buf.buffer) {
        vkDestroyBuffer(dev.vk_device, buf.buffer, nullptr);
        buf.buffer = VK_NULL_HANDLE;
    }
    if (buf.memory) {
        vkFreeMemory(dev.vk_device, buf.memory, nullptr);
        buf.memory = VK_NULL_HANDLE;
    }
    buf.mapped = nullptr;
    buf.size = 0;
    buf.host_visible = false;
}

static bool vk_buf_reserve(moe_cache_vulkan_device & dev, vk_buf & buf,
                           VkDeviceSize required, VkBufferUsageFlags usage,
                           VkMemoryPropertyFlags props) {
    if (buf.size >= required) {
        return true;
    }
    const size_t capacity = moe_cache_growth_capacity((size_t)buf.size, (size_t)required);
    if (capacity == 0) {
        return false;
    }
    vk_buf next;
    if (!vk_buf_create(dev, capacity, usage, props, next)) {
        return false;
    }
    vk_buf_destroy(dev, buf);
    buf = next;
    return true;
}

// Submit one one-time command buffer and wait for it.
template <typename F>
static bool vk_submit_and_wait(moe_cache_vulkan_device & dev, F record) {
    VkCommandBufferAllocateInfo ai = {};
    ai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
    ai.commandPool = dev.vk_cmd_pool;
    ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    ai.commandBufferCount = 1;

    VkCommandBuffer cmd = VK_NULL_HANDLE;
    if (vkAllocateCommandBuffers(dev.vk_device, &ai, &cmd) != VK_SUCCESS) {
        return false;
    }

    VkCommandBufferBeginInfo bi = {};
    bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;

    bool ok = vkBeginCommandBuffer(cmd, &bi) == VK_SUCCESS;
    if (ok) {
        ok = record(cmd);
    }
    if (ok) {
        ok = vkEndCommandBuffer(cmd) == VK_SUCCESS;
    }
    if (ok) {
        VkSubmitInfo si = {};
        si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
        si.commandBufferCount = 1;
        si.pCommandBuffers = &cmd;
        ok = vkQueueSubmit(dev.vk_queue, 1, &si, VK_NULL_HANDLE) == VK_SUCCESS;
    }
    if (ok) {
        ok = vkQueueWaitIdle(dev.vk_queue) == VK_SUCCESS;
    }
    vkFreeCommandBuffers(dev.vk_device, dev.vk_cmd_pool, 1, &cmd);
    return ok;
}

// Copy host data into a buffer. Direct memcpy when the buffer is
// host-visible; otherwise stage through the shared staging buffer.
static bool vk_buf_upload(moe_cache_vulkan_device & dev, vk_buf & buf,
                          VkDeviceSize offset, const void * src, VkDeviceSize bytes) {
    if (bytes == 0) {
        return true;
    }
    if (buf.host_visible) {
        memcpy((char *)buf.mapped + offset, src, bytes);
        return true;
    }
    if (!vk_buf_reserve(dev, dev.staging, bytes,
                        VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
                        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                        VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)) {
        return false;
    }
    memcpy(dev.staging.mapped, src, bytes);
    return vk_submit_and_wait(dev, [&](VkCommandBuffer cmd) {
        VkBufferCopy region = {};
        region.srcOffset = 0;
        region.dstOffset = offset;
        region.size = bytes;
        vkCmdCopyBuffer(cmd, dev.staging.buffer, buf.buffer, 1, &region);
        return true;
    });
}

// Copy device data back to host. Direct memcpy when the buffer is
// host-visible; otherwise stage through the shared staging buffer.
static bool vk_buf_download(moe_cache_vulkan_device & dev, vk_buf & buf,
                            VkDeviceSize offset, void * dst, VkDeviceSize bytes) {
    if (bytes == 0) {
        return true;
    }
    if (buf.host_visible) {
        memcpy(dst, (const char *)buf.mapped + offset, bytes);
        return true;
    }
    if (!vk_buf_reserve(dev, dev.staging, bytes,
                        VK_BUFFER_USAGE_TRANSFER_DST_BIT,
                        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                        VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)) {
        return false;
    }
    if (!vk_submit_and_wait(dev, [&](VkCommandBuffer cmd) {
        VkBufferCopy region = {};
        region.srcOffset = offset;
        region.dstOffset = 0;
        region.size = bytes;
        vkCmdCopyBuffer(cmd, buf.buffer, dev.staging.buffer, 1, &region);
        return true;
    })) {
        return false;
    }
    memcpy(dst, dev.staging.mapped, bytes);
    return true;
}

// ---------------------------------------------------------------------------
// Pipeline loading from embedded SPIR-V
// ---------------------------------------------------------------------------

static VkPipeline vk_create_pipeline(moe_cache_vulkan_device & dev,
                                     const unsigned char * spv, uint64_t spv_len) {
    VkShaderModuleCreateInfo smci = {};
    smci.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    smci.codeSize = spv_len;
    smci.pCode = (const uint32_t *)spv;

    VkShaderModule module = VK_NULL_HANDLE;
    if (vkCreateShaderModule(dev.vk_device, &smci, nullptr, &module) != VK_SUCCESS) {
        return VK_NULL_HANDLE;
    }

    VkComputePipelineCreateInfo cpci = {};
    cpci.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
    cpci.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    cpci.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
    cpci.stage.module = module;
    cpci.stage.pName = "main";
    cpci.layout = dev.pipeline_layout;

    VkPipeline pipeline = VK_NULL_HANDLE;
    vkCreateComputePipelines(dev.vk_device, VK_NULL_HANDLE, 1, &cpci, nullptr, &pipeline);
    vkDestroyShaderModule(dev.vk_device, module, nullptr);
    return pipeline;
}

// Create a moe-cache kernel pipeline, logging the name on failure.
static VkPipeline vk_moe_pipeline_create(moe_cache_vulkan_device & dev,
                                         const char * name,
                                         const unsigned char * spv, uint64_t spv_len) {
    VkPipeline pipeline = vk_create_pipeline(dev, spv, spv_len);
    if (!pipeline) {
        MOE_CACHE_LOG("[moe-cache] Vulkan: moe cache kernel missing: %s\n", name);
    }
    return pipeline;
}

static bool vk_load_pipelines(moe_cache_vulkan_device & dev) {
    // descriptor set layout: 4 storage buffers + 1 uniform buffer
    VkDescriptorSetLayoutBinding bindings[5] = {};
    for (int i = 0; i < 4; i++) {
        bindings[i].binding = i;
        bindings[i].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
        bindings[i].descriptorCount = 1;
        bindings[i].stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
    }
    bindings[4].binding = 4;
    bindings[4].descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
    bindings[4].descriptorCount = 1;
    bindings[4].stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;

    VkDescriptorSetLayoutCreateInfo dslci = {};
    dslci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
    dslci.bindingCount = 5;
    dslci.pBindings = bindings;
    if (vkCreateDescriptorSetLayout(dev.vk_device, &dslci, nullptr, &dev.ds_layout) != VK_SUCCESS) {
        return false;
    }

    VkPipelineLayoutCreateInfo plci = {};
    plci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    plci.setLayoutCount = 1;
    plci.pSetLayouts = &dev.ds_layout;
    if (vkCreatePipelineLayout(dev.vk_device, &plci, nullptr, &dev.pipeline_layout) != VK_SUCCESS) {
        return false;
    }

    dev.pipeline_q8_0 = vk_moe_pipeline_create(dev, "moe_cache_mv_q8_0", moe_cache_mv_q8_0_data, moe_cache_mv_q8_0_len);
    dev.pipeline_q4_0 = vk_moe_pipeline_create(dev, "moe_cache_mv_q4_0", moe_cache_mv_q4_0_data, moe_cache_mv_q4_0_len);
    dev.pipeline_q4_K = vk_moe_pipeline_create(dev, "moe_cache_mv_q4_K", moe_cache_mv_q4_K_data, moe_cache_mv_q4_K_len);
    dev.pipeline_q6_K = vk_moe_pipeline_create(dev, "moe_cache_mv_q6_K", moe_cache_mv_q6_K_data, moe_cache_mv_q6_K_len);
    dev.pipeline_q5_K = vk_moe_pipeline_create(dev, "moe_cache_mv_q5_K", moe_cache_mv_q5_K_data, moe_cache_mv_q5_K_len);
    dev.pipeline_q1_0 = vk_moe_pipeline_create(dev, "moe_cache_mv_q1_0", moe_cache_mv_q1_0_data, moe_cache_mv_q1_0_len);
    dev.pipeline_q2_0 = vk_moe_pipeline_create(dev, "moe_cache_mv_q2_0", moe_cache_mv_q2_0_data, moe_cache_mv_q2_0_len);
    dev.pipeline_q4_1 = vk_moe_pipeline_create(dev, "moe_cache_mv_q4_1", moe_cache_mv_q4_1_data, moe_cache_mv_q4_1_len);
    dev.pipeline_q5_0 = vk_moe_pipeline_create(dev, "moe_cache_mv_q5_0", moe_cache_mv_q5_0_data, moe_cache_mv_q5_0_len);
    dev.pipeline_q5_1 = vk_moe_pipeline_create(dev, "moe_cache_mv_q5_1", moe_cache_mv_q5_1_data, moe_cache_mv_q5_1_len);
    dev.pipeline_q2_K = vk_moe_pipeline_create(dev, "moe_cache_mv_q2_K", moe_cache_mv_q2_K_data, moe_cache_mv_q2_K_len);
    dev.pipeline_q3_K = vk_moe_pipeline_create(dev, "moe_cache_mv_q3_K", moe_cache_mv_q3_K_data, moe_cache_mv_q3_K_len);
    dev.pipeline_iq2_xxs = vk_moe_pipeline_create(dev, "moe_cache_mv_iq2_xxs", moe_cache_mv_iq2_xxs_data, moe_cache_mv_iq2_xxs_len);
    dev.pipeline_iq2_xs = vk_moe_pipeline_create(dev, "moe_cache_mv_iq2_xs", moe_cache_mv_iq2_xs_data, moe_cache_mv_iq2_xs_len);
    dev.pipeline_iq2_s = vk_moe_pipeline_create(dev, "moe_cache_mv_iq2_s", moe_cache_mv_iq2_s_data, moe_cache_mv_iq2_s_len);
    dev.pipeline_iq3_xxs = vk_moe_pipeline_create(dev, "moe_cache_mv_iq3_xxs", moe_cache_mv_iq3_xxs_data, moe_cache_mv_iq3_xxs_len);
    dev.pipeline_iq3_s = vk_moe_pipeline_create(dev, "moe_cache_mv_iq3_s", moe_cache_mv_iq3_s_data, moe_cache_mv_iq3_s_len);
    dev.pipeline_iq1_s = vk_moe_pipeline_create(dev, "moe_cache_mv_iq1_s", moe_cache_mv_iq1_s_data, moe_cache_mv_iq1_s_len);
    dev.pipeline_iq1_m = vk_moe_pipeline_create(dev, "moe_cache_mv_iq1_m", moe_cache_mv_iq1_m_data, moe_cache_mv_iq1_m_len);
    dev.pipeline_iq4_nl = vk_moe_pipeline_create(dev, "moe_cache_mv_iq4_nl", moe_cache_mv_iq4_nl_data, moe_cache_mv_iq4_nl_len);
    dev.pipeline_iq4_xs = vk_moe_pipeline_create(dev, "moe_cache_mv_iq4_xs", moe_cache_mv_iq4_xs_data, moe_cache_mv_iq4_xs_len);
    dev.pipeline_mxfp4 = vk_moe_pipeline_create(dev, "moe_cache_mv_mxfp4", moe_cache_mv_mxfp4_data, moe_cache_mv_mxfp4_len);
    dev.pipeline_nvfp4 = vk_moe_pipeline_create(dev, "moe_cache_mv_nvfp4", moe_cache_mv_nvfp4_data, moe_cache_mv_nvfp4_len);
    if (!dev.pipeline_q8_0 || !dev.pipeline_q4_0 || !dev.pipeline_q4_K || !dev.pipeline_q6_K || !dev.pipeline_q5_K ||
        !dev.pipeline_q1_0 || !dev.pipeline_q2_0 || !dev.pipeline_q4_1 || !dev.pipeline_q5_0 || !dev.pipeline_q5_1 ||
        !dev.pipeline_q2_K || !dev.pipeline_q3_K || !dev.pipeline_iq2_xxs || !dev.pipeline_iq2_xs || !dev.pipeline_iq2_s ||
        !dev.pipeline_iq3_xxs || !dev.pipeline_iq3_s || !dev.pipeline_iq1_s || !dev.pipeline_iq1_m || !dev.pipeline_iq4_nl ||
        !dev.pipeline_iq4_xs || !dev.pipeline_mxfp4 || !dev.pipeline_nvfp4) {
        return false;
    }

    VkDescriptorPoolSize pool_sizes[2] = {};
    pool_sizes[0].type = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    pool_sizes[0].descriptorCount = 4 * 4;
    pool_sizes[1].type = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
    pool_sizes[1].descriptorCount = 4;

    VkDescriptorPoolCreateInfo dpci = {};
    dpci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
    dpci.maxSets = 4;
    dpci.poolSizeCount = 2;
    dpci.pPoolSizes = pool_sizes;
    if (vkCreateDescriptorPool(dev.vk_device, &dpci, nullptr, &dev.ds_pool) != VK_SUCCESS) {
        return false;
    }

    VkDescriptorSetAllocateInfo dsai = {};
    dsai.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
    dsai.descriptorPool = dev.ds_pool;
    dsai.descriptorSetCount = 1;
    dsai.pSetLayouts = &dev.ds_layout;
    if (vkAllocateDescriptorSets(dev.vk_device, &dsai, &dev.ds) != VK_SUCCESS) {
        return false;
    }
    return true;
}

// Create the command pool and compile the moe-cache pipelines on first use.
// session_create only keeps bookkeeping state, so a context that never uses
// the cache pays no GPU setup cost.
static bool vk_device_ensure_ready(moe_cache_vulkan_device & dev, size_t budget_mb) {
    std::call_once(dev.init_once, [&]() {
        VkCommandPoolCreateInfo cpci = {};
        cpci.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
        cpci.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
        cpci.queueFamilyIndex = dev.vk_queue_family;
        if (vkCreateCommandPool(dev.vk_device, &cpci, nullptr, &dev.vk_cmd_pool) != VK_SUCCESS) {
            dev.dead.store(true);
            return;
        }
        if (!vk_load_pipelines(dev)) {
            MOE_CACHE_LOG("[moe-cache] Vulkan pipeline creation failed\n");
            dev.free_resources();
            dev.dead.store(true);
            return;
        }
        dev.init_ok = true;
        MOE_CACHE_LOG("[moe-cache] Vulkan session ready (budget=%zu MiB, %s)\n",
                budget_mb, dev.host_mapped ? "host-mapped" : "device-local");
    });
    return dev.init_ok;
}

// ---------------------------------------------------------------------------
// Quantize activations to Q8_1 (scalar, reference quality)
// ---------------------------------------------------------------------------

static void vk_quantize_act_q8_1(const float * src, block_q8_1 * dst,
                                 int64_t n, int64_t padded_n) {
    const int nb = (int)(padded_n / QK8_1);
    for (int ib = 0; ib < nb; ib++) {
        float amax = 0.0f;
        for (int i = 0; i < QK8_1; i++) {
            const int64_t idx = (int64_t)ib * QK8_1 + i;
            const float v = (idx < n) ? src[idx] : 0.0f;
            amax = fmaxf(amax, fabsf(v));
        }
        const float d = amax / 127.0f;
        const float id = (d > 0.0f) ? (1.0f / d) : 0.0f;
        float sum = 0.0f;
        for (int i = 0; i < QK8_1; i++) {
            const int64_t idx = (int64_t)ib * QK8_1 + i;
            const float v = (idx < n) ? src[idx] : 0.0f;
            const int8_t q = (int8_t)roundf(v * id);
            dst[ib].qs[i] = q;
            sum += (float)q * d;
        }
        dst[ib].d = ggml_fp32_to_fp16(d);
        dst[ib].s = ggml_fp32_to_fp16(sum);
    }
}

// ---------------------------------------------------------------------------
// Query functions
// ---------------------------------------------------------------------------

static int vk_moe_query_config(int automatic, size_t budget_mib,
                               ggml_moe_cache_config * result) {
    if (!result) {
        return 0;
    }

    moe_cache_config config = moe_cache_read_config();
    if (automatic >= 0) {
        config.enabled = true;
        config.automatic = automatic != 0;
        moe_cache_apply_mode_defaults(config);
        config.min_compute_capability =
            moe_cache_min_compute_capability(config.automatic);
    }
    if (budget_mib > 0) {
        config.budget_mb = budget_mib;
    }
    if (!config.enabled || config.budget_mb > (SIZE_MAX >> 20) ||
        config.reserve_mb > (SIZE_MAX >> 20)) {
        return 0;
    }

    result->budget_bytes = config.budget_mb << 20;
    result->reserve_bytes = config.reserve_mb << 20;
    result->minimum_slab_bytes = config.minimum_slab_bytes;
    result->min_expert_bytes = config.min_expert_bytes;
    result->min_expert_explicit = config.min_expert_explicit;
    result->max_batch = config.max_batch;
    result->min_compute_capability = config.min_compute_capability;
    result->min_devices = 1; // Vulkan session uses a single device
    result->overlap_cpu_rows = config.overlap_cpu_rows;
    return 1;
}

static int vk_moe_query_device(void * opaque, const ggml_moe_cache_config * config,
                               ggml_moe_cache_device_caps * result) {
    if (!opaque || !config || !result || !g_moe_cache_owner) {
        return 0;
    }

    ggml_backend_dev_t device = (ggml_backend_dev_t)opaque;
    ggml_backend_reg_t reg = ggml_backend_dev_backend_reg(device);
    if ((const void *)reg != g_moe_cache_owner) {
        return 0;
    }

    result->logical_device = 0;
    result->physical_device = 0;
    result->compute_capability = 800; // ~ Ampere-class; no CC on Vulkan
    result->min_expert_bytes = config->min_expert_explicit
        ? config->min_expert_bytes
        : moe_cache_default_min_expert_bytes(800);
    return 1;
}

static int vk_moe_query_shape(int wtype, int64_t n_in, int64_t n_out,
                              int64_t n_expert, size_t expert_size,
                              ggml_moe_cache_shape_caps * result) {
    if (!result || n_in <= 0 || n_out <= 0 || n_expert <= 0) {
        return 0;
    }
    // canonical list from ggml-backend-moe-cache.h; single source of truth
    if (!ggml_moe_cache_wtype_supported(wtype)) {
        return 0;
    }

    const size_t row_size = ggml_row_size((ggml_type)wtype, n_in);
    if (row_size == 0 || (uint64_t)n_out > SIZE_MAX / row_size ||
        expert_size != (size_t)n_out * row_size ||
        expert_size > SIZE_MAX / moe_cache_pool_slots_min) {
        return 0;
    }

    const size_t out_bytes =
        moe_cache_node_rows_max * (size_t)n_out * sizeof(float);
    const size_t act_q8_bytes =
        moe_cache_node_rows_max *
        (size_t)((n_in + QK8_1 - 1) / QK8_1) * sizeof(block_q8_1);
    const size_t scratch_bytes = out_bytes + act_q8_bytes;
    const size_t pool_bytes = expert_size * moe_cache_pool_slots_min;
    if (pool_bytes > SIZE_MAX - scratch_bytes) {
        return 0;
    }
    result->scratch_bytes = scratch_bytes;
    result->pool_bytes = pool_bytes;
    result->minimum_bytes = scratch_bytes + pool_bytes;
    return 1;
}

// ---------------------------------------------------------------------------
// Pool lifecycle
// ---------------------------------------------------------------------------

static moe_cache_pool * vk_moe_find_or_create_pool(
        moe_cache_vulkan_device & dev, moe_cache_session & session,
        size_t expert_size, int wtype, int64_t n_expert, size_t budget_bytes) {
    const int existing = moe_cache_find_pool(dev, expert_size, wtype);
    if (existing >= 0) {
        return dev.pools[existing].get();
    }

    if (moe_cache_fail(session, "slab")) {
        MOE_CACHE_LOG("[moe-cache] Vulkan: skipped %zu KiB expert pool: allocation failed\n",
                expert_size >> 10);
        return nullptr;
    }

    size_t slots = budget_bytes / expert_size;
    if (slots < moe_cache_pool_slots_min) {
        return nullptr;
    }
    if ((uint64_t)n_expert > 0 && slots > (size_t)n_expert) {
        slots = (size_t)n_expert;
    }
    if (slots < moe_cache_pool_slots_min) {
        return nullptr;
    }
    if (slots > (size_t)INT_MAX) {
        slots = INT_MAX;
    }
    const size_t slab_bytes = slots * expert_size;

    vk_buf slab_buf;
    VkBufferUsageFlags usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
    VkMemoryPropertyFlags props = dev.host_mapped
        ? (VkMemoryPropertyFlags)(VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT |
                                  VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                                  VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)
        : (VkMemoryPropertyFlags)VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT;
    if (!dev.host_mapped) {
        usage |= VK_BUFFER_USAGE_TRANSFER_DST_BIT;
    }
    if (!vk_buf_create(dev, slab_bytes, usage, props, slab_buf)) {
        MOE_CACHE_LOG("[moe-cache] Vulkan: failed to allocate %zu MiB expert pool\n",
                slab_bytes >> 20);
        return nullptr;
    }

    try {
        std::unique_ptr<moe_cache_pool> pool(new moe_cache_pool());
        pool->expert_size = expert_size;
        pool->wtype = wtype;
        pool->slab = dev.host_mapped ? (char *)slab_buf.mapped : nullptr;
        pool->n_slots = (int)slots;
        pool->covers_all_entries = (uint64_t)slots >= (uint64_t)n_expert;
        pool->slots.resize(slots);
        pool->free_slots.reserve(slots);
        pool->map.reserve(slots);
        for (int index = (int)slots - 1; index >= 0; index--) {
            pool->free_slots.push_back(index);
        }
        dev.allocated_bytes += slab_bytes;
        dev.pools.push_back(std::move(pool));
        dev.pool_buffers.push_back(slab_buf);
        MOE_CACHE_LOG("[moe-cache] Vulkan%d pool[%d]: type=%s expert=%zu KiB slots=%zu entries=%lld coverage=%s total=%zu MiB\n",
                dev.physical, (int)dev.pools.size() - 1,
                ggml_type_name((ggml_type)wtype), expert_size >> 10,
                slots, (long long)n_expert,
                dev.pools.back()->covers_all_entries ? "complete" : "partial",
                slab_bytes >> 20);
        bool expected = false;
        if (session.enabled_announced.compare_exchange_strong(expected, true)) {
            MOE_CACHE_LOG("[moe-cache] enabled: first pool allocated on Vulkan%d\n",
                    dev.physical);
        }
        return dev.pools.back().get();
    } catch (...) {
        vk_buf_destroy(dev, slab_buf);
        return nullptr;
    }
}

// ---------------------------------------------------------------------------
// Session lifecycle
// ---------------------------------------------------------------------------

static void * vk_moe_session_create(void * const * backends, int n_backends,
                                    const ggml_moe_cache_config * supplied_config) {
    try {
        moe_cache_config config = moe_cache_read_config();
        if (supplied_config) {
            constexpr size_t MiB = 1024 * 1024;
            if (supplied_config->budget_bytes % MiB != 0 ||
                supplied_config->reserve_bytes % MiB != 0 ||
                supplied_config->minimum_slab_bytes % MiB != 0 ||
                supplied_config->min_expert_bytes == 0 ||
                supplied_config->min_expert_explicit < 0 ||
                supplied_config->min_expert_explicit > 1 ||
                supplied_config->max_batch < 1 ||
                supplied_config->max_batch > moe_cache_batch_max ||
                supplied_config->min_devices < 1 ||
                supplied_config->min_compute_capability < 0 ||
                supplied_config->min_compute_capability > 999 ||
                supplied_config->overlap_cpu_rows < -1 ||
                supplied_config->overlap_cpu_rows > 8) {
                return nullptr;
            }
            config.enabled = true;
            config.automatic = supplied_config->minimum_slab_bytes > 0;
            config.budget_mb = supplied_config->budget_bytes / MiB;
            config.reserve_mb = supplied_config->reserve_bytes / MiB;
            config.minimum_slab_bytes = supplied_config->minimum_slab_bytes;
            config.min_expert_bytes = supplied_config->min_expert_bytes;
            config.min_expert_explicit = supplied_config->min_expert_explicit;
            config.max_batch = supplied_config->max_batch;
            config.min_compute_capability = supplied_config->min_compute_capability;
            config.overlap_cpu_rows = supplied_config->overlap_cpu_rows;
        }
        if (!config.enabled) {
            return nullptr;
        }
        // A zero budget can never create a pool; bail before querying
        // VkPhysicalDeviceMemoryProperties and creating the device object.
        if (!supplied_config && config.budget_mb == 0) {
            return nullptr;
        }

        // Find the Vulkan backend among the scheduler's backends.
        ggml_backend_t vk_backend = nullptr;
        for (int i = 0; i < n_backends; i++) {
            ggml_backend_t be = (ggml_backend_t)backends[i];
            if (be && ggml_backend_is_vk(be)) {
                vk_backend = be;
                break;
            }
        }
        if (!vk_backend) {
            MOE_CACHE_LOG("[moe-cache] no Vulkan device found\n");
            return nullptr;
        }

        VkDevice vk_device = ggml_backend_vk_get_device_handle(vk_backend);
        VkQueue vk_queue = ggml_backend_vk_get_queue_handle(vk_backend);
        VkPhysicalDevice vk_physical = ggml_backend_vk_get_physical_device(vk_backend);
        const uint32_t queue_family = ggml_backend_vk_get_queue_family(vk_backend);
        if (!vk_device || !vk_queue || !vk_physical) {
            MOE_CACHE_LOG("[moe-cache] Vulkan backend has no usable handles\n");
            return nullptr;
        }

        std::unique_ptr<moe_cache_session> session(new (std::nothrow) moe_cache_session());
        if (!session) {
            return nullptr;
        }
        session->config = std::move(config);

        std::unique_ptr<moe_cache_vulkan_device> dev(new (std::nothrow)
                moe_cache_vulkan_device(0, 0));
        if (!dev) {
            return nullptr;
        }
        dev->vk_device = vk_device;
        dev->vk_queue = vk_queue;
        dev->vk_physical = vk_physical;
        dev->vk_queue_family = queue_family;

        // Detect UMA: a memory type that is device-local AND host-visible.
        VkPhysicalDeviceMemoryProperties mem_props;
        vkGetPhysicalDeviceMemoryProperties(vk_physical, &mem_props);
        for (uint32_t i = 0; i < mem_props.memoryTypeCount; i++) {
            const VkMemoryPropertyFlags flags = mem_props.memoryTypes[i].propertyFlags;
            if ((flags & (VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT |
                          VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                          VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)) ==
                        (VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT |
                         VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                         VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)) {
                dev->host_mapped = true;
                break;
            }
        }

        // GPU resources (command pool, pipelines) are created lazily on the
        // first begin; a context that never uses the cache allocates none.
        session->devices.push_back(std::move(dev));

        moe_cache_session * result = session.get();
        try {
            std::lock_guard<std::mutex> lock(g_registry_mu);
            g_sessions.insert(result);
            g_session_count.store(g_sessions.size(), std::memory_order_release);
        } catch (...) {
            return nullptr;
        }
        session.release();
        return result;
    } catch (...) {
        MOE_CACHE_LOG("[moe-cache] Vulkan session creation failed\n");
        return nullptr;
    }
}

// Teardown statistics, same field names as CUDA so the log contract is
// backend-independent. Only logged when the session did any cache work.
static void vk_moe_log_stats(moe_cache_vulkan_device & dev) {
    size_t used = 0;
    size_t slots = 0;
    for (const auto & pool_ptr : dev.pools) {
        const moe_cache_pool & pool = *pool_ptr;
        slots += pool.n_slots;
        used += pool.n_slots - pool.free_slots.size();
    }
    const long long total = dev.hits + dev.misses;
    MOE_CACHE_LOG("[moe-cache] Vulkan%d hits=%lld/%lld (%.1f%%) used=%zu/%zu enqueued=%lld filled=%lld fill-fail=%lld evictions=%lld skips=%lld admission=%lld dispatch-fail=%lld collect-fail=%lld bypass=%lld\n",
            dev.physical, dev.hits, total,
            total ? 100.0 * (double)dev.hits / (double)total : 0.0,
            used, slots, dev.inserts, dev.fills, dev.fill_failures,
            dev.evictions, dev.insert_skips, dev.admission_skips,
            dev.dispatch_failures, dev.collect_failures, dev.contention_bypasses);
}

static void vk_moe_session_destroy(void * opaque) {
    moe_cache_session * session = (moe_cache_session *)opaque;
    if (!session) {
        return;
    }
    {
        // Stop new scopes/nodes and wait for in-flight work to drain before
        // freeing device resources a CPU worker may still be using.
        std::unique_lock<std::mutex> lock(session->mu);
        session->stopping = true;
        session->cv.notify_all();
        session->idle_cv.wait(lock, [&] {
            return session->active_scopes == 0 && session->active_nodes == 0;
        });
    }
    {
        std::lock_guard<std::mutex> lock(g_registry_mu);
        g_sessions.erase(session);
        g_session_count.store(g_sessions.size(), std::memory_order_release);
    }
    for (auto & dev_ptr : session->devices) {
        moe_cache_vulkan_device & dev =
            static_cast<moe_cache_vulkan_device &>(*dev_ptr);
        if (dev.nodes > 0 || dev.dispatch_failures > 0 ||
            dev.collect_failures > 0) {
            vk_moe_log_stats(dev);
        }
    }
    delete session;
}

static void vk_moe_session_enter(void * opaque) {
    if (g_session_suppressed > 0) {
        g_session_suppressed++;
        return;
    }

    moe_cache_session * session = (moe_cache_session *)opaque;
    if (!session || session->dormant.load() || session->stopping) {
        if (g_session_stack.empty()) {
            return;
        }
        try {
            g_session_stack.push_back({session, nullptr});
        } catch (...) {
            g_session_suppressed++;
        }
        return;
    }
    try {
        g_session_stack.push_back({session, session});
    } catch (...) {
        g_session_suppressed++;
        return;
    }
    std::lock_guard<std::mutex> lock(session->mu);
    session->active_scopes++;
}

static void vk_moe_session_leave(void * opaque) {
    if (g_session_suppressed > 0) {
        g_session_suppressed--;
        return;
    }
    moe_cache_session * expected = (moe_cache_session *)opaque;
    auto found = std::find_if(
            g_session_stack.rbegin(), g_session_stack.rend(),
            [expected](const moe_cache_scope_frame & frame) {
                return frame.requested == expected;
            });
    if (found == g_session_stack.rend()) {
        return;
    }
    moe_cache_session * active = found->active;
    g_session_stack.erase(std::next(found).base());
    if (active) {
        std::lock_guard<std::mutex> lock(active->mu);
        if (active->active_scopes > 0) {
            active->active_scopes--;
        }
        active->idle_cv.notify_all();
    }
}

// ---------------------------------------------------------------------------
// Begin: find pool, create node. Pools are created lazily on first use.
// ---------------------------------------------------------------------------

static void * vk_moe_begin(const char * name, const void * host_base,
                           size_t expert_size, int64_t n_in, int64_t n_out,
                           int wtype, int64_t n_expert, int64_t n_tokens,
                           int64_t n_rows) {
    if (g_session_suppressed > 0 || g_session_stack.empty()) {
        return nullptr;
    }
    moe_cache_session * session = g_session_stack.back().active;
    if (!session || session->stopping || session->dormant) {
        return nullptr;
    }
    if (!name || !host_base || !moe_cache_tensor_name_supported(name) ||
        n_tokens < 1 || expert_size < session->config.min_expert_bytes ||
        n_in <= 0 || n_out <= 0 || n_expert <= 0 ||
        !ggml_moe_cache_wtype_supported(wtype)) {
        return nullptr;
    }
    if (n_rows < n_tokens || n_rows % n_tokens != 0 ||
        n_tokens > session->config.max_batch ||
        n_rows > moe_cache_node_rows_max) {
        return nullptr;
    }

    const size_t row_size = ggml_row_size((ggml_type)wtype, n_in);
    if (row_size == 0 || (uint64_t)n_out > SIZE_MAX / row_size ||
        expert_size != (size_t)n_out * row_size ||
        expert_size > SIZE_MAX / moe_cache_pool_slots_min) {
        return nullptr;
    }

    if (session->devices.empty()) {
        return nullptr;
    }
    moe_cache_vulkan_device & dev =
        static_cast<moe_cache_vulkan_device &>(*session->devices[0]);
    // A zero budget can never create a pool; skip GPU setup entirely.
    if (session->config.budget_mb == 0) {
        return nullptr;
    }
    // Create the command pool and compile the pipelines on first use, before
    // the dispatch lock so a one-time compile does not block other workers.
    if (!vk_device_ensure_ready(dev, session->config.budget_mb)) {
        return nullptr;
    }

    std::unique_lock<std::mutex> dispatch_lock;
    try {
        dispatch_lock = std::unique_lock<std::mutex>(
                dev.dispatch_mu, std::try_to_lock);
    } catch (...) {
        dev.contention_bypasses++;
        return nullptr;
    }
    if (!dispatch_lock.owns_lock()) {
        dev.contention_bypasses++;
        return nullptr;
    }
    if (dev.dead.load()) {
        return nullptr;
    }

    moe_cache_log_configuration(*session);
    const size_t budget_bytes = session->config.budget_mb << 20;
    moe_cache_pool * pool = vk_moe_find_or_create_pool(
            dev, *session, expert_size, wtype, n_expert, budget_bytes);
    if (!pool) {
        return nullptr;
    }
    const int pool_index = moe_cache_find_pool(dev, expert_size, wtype);
    if (pool_index < 0) {
        return nullptr;
    }

    std::unique_ptr<moe_cache_node> node(new (std::nothrow) moe_cache_node());
    if (!node) {
        return nullptr;
    }
    node->session = session;
    node->device = &dev;
    node->pool = pool;
    node->pool_index = pool_index;
    node->host_base = host_base;
    node->expert_size = expert_size;
    node->n_in = n_in;
    node->n_out = n_out;
    node->n_expert = n_expert;
    node->n_tokens = n_tokens;
    node->wtype = wtype;
    node->dispatch_lock = std::move(dispatch_lock);

    // Own the node for the caller; destroy() waits for this to reach zero.
    std::lock_guard<std::mutex> session_lock(session->mu);
    session->active_nodes++;
    return node.release();
}

// ---------------------------------------------------------------------------
// Plan: mark cache hits; sync-fill a bounded number of misses into the slab
// and serve them in this node. slot_indices[i] >= 0 means cache-served.
// ---------------------------------------------------------------------------

static int vk_moe_plan(void * opaque, const int32_t * ids, int n_ids,
                       int32_t * slot_indices) {
    moe_cache_node * node = (moe_cache_node *)opaque;
    if (!node || !ids || !slot_indices || n_ids < 0 ||
        n_ids > moe_cache_node_rows_max || node->planned) {
        return 0;
    }
    node->planned = true;
    for (int index = 0; index < n_ids; index++) {
        slot_indices[index] = -1;
    }

    moe_cache_session & session = *node->session;
    moe_cache_vulkan_device & dev =
        static_cast<moe_cache_vulkan_device &>(*node->device);
    moe_cache_pool & pool = *node->pool;
    int hits = 0;

    std::unique_lock<std::mutex> lock(session.mu);
    if (session.stopping) {
        return 0;
    }

    // First pass: count misses and bound fills.
    int n_misses = 0;
    int n_fills = 0;
    const size_t max_fill_bytes = session.config.queue_mb << 20;
    if (max_fill_bytes == 0 || node->expert_size > max_fill_bytes) {
        n_fills = 0;
    } else {
        n_fills = std::min((int)session.config.inserts_per_plan,
                           (int)(max_fill_bytes / node->expert_size));
    }
    for (int index = 0; index < n_ids; index++) {
        const int32_t expert = ids[index];
        if (expert < 0 || expert >= node->n_expert || dev.dead.load()) {
            continue;
        }
        const moe_cache_key key{node->host_base, expert};
        if (pool.map.find(key) == pool.map.end() ||
            pool.slots[pool.map.at(key)].state != moe_cache_slot_state::valid) {
            n_misses++;
        }
    }
    const int fill_budget = std::min(n_misses, n_fills);

    // Pre-fill stage: host-visible slabs are filled inline; device-local
    // slabs are filled through the staging buffer in one batch. Pending
    // slots stay in 'copying' until the batch transfer is confirmed so a
    // failed submit can never publish stale slab bytes as a hit.
    struct pending_fill {
        int slot;
        int index; // ids[] / slot_indices[] position
    };
    std::vector<pending_fill> pending;
    vk_buf * slab_buf = nullptr;
    if (node->pool_index >= 0 &&
        node->pool_index < (int)dev.pool_buffers.size()) {
        slab_buf = &dev.pool_buffers[node->pool_index];
    }

    if (fill_budget > 0 && !dev.host_mapped) {
        // reserve staging for all payloads
        const size_t fill_bytes = (size_t)fill_budget * node->expert_size;
        if (!vk_buf_reserve(dev, dev.staging, fill_bytes,
                            VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
                            VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                            VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)) {
            return hits; // no fills, keep hits
        }
    }

    int fills_done = 0;
    for (int index = 0; index < n_ids; index++) {
        const int32_t expert = ids[index];
        if (expert < 0 || expert >= node->n_expert || dev.dead.load()) {
            continue;
        }

        const moe_cache_key key{node->host_base, expert};
        auto found = pool.map.find(key);
        if (found != pool.map.end() &&
            pool.slots[found->second].state == moe_cache_slot_state::valid) {
            const int slot_index = found->second;
            moe_cache_slot & slot = pool.slots[slot_index];
            slot.readers++;
            slot.uses++;
            moe_cache_lru_remove(pool, slot_index);
            moe_cache_lru_push_back(pool, slot_index);
            node->pins[node->n_pins++] = {&pool, slot_index};
            slot_indices[index] = slot_index;
            dev.hits++;
            hits++;
            continue;
        }

        // miss
        dev.misses++;
        if (moe_cache_fail(session, "insert")) {
            dev.fill_failures++;
            continue;
        }
        if (fills_done >= fill_budget) {
            continue; // CPU handles this row
        }
        fills_done++;

        int slot_index = -1;
        if (!pool.free_slots.empty()) {
            slot_index = pool.free_slots.back();
            pool.free_slots.pop_back();
        } else {
            int candidate = moe_cache_pick_victim(pool, session.config.hot_uses);
            if (candidate < 0) {
                continue; // all slots pinned; CPU handles this row
            }
            slot_index = candidate;
            const bool sacrificed_hot =
                (int)pool.slots[slot_index].uses > session.config.hot_uses;
            moe_cache_slot_reset(pool, slot_index, false);
            dev.evictions++;
            if (sacrificed_hot) {
                dev.heat_evictions++;
            }
        }

        moe_cache_slot & slot = pool.slots[slot_index];
        slot.key = key;
        slot.generation++;
        slot.state = moe_cache_slot_state::copying;
        const void * source =
            (const char *)node->host_base + (size_t)expert * node->expert_size;
        try {
            pool.map.emplace(key, slot_index);
        } catch (...) {
            moe_cache_slot_reset(pool, slot_index, true);
            dev.insert_skips++;
            continue;
        }

        if (dev.host_mapped && pool.slab) {
            memcpy(pool.slab + (size_t)slot_index * node->expert_size,
                   source, node->expert_size);
            // Host-mapped fill is a plain memcpy that cannot fail; promote now.
            slot.state = moe_cache_slot_state::valid;
            moe_cache_lru_push_back(pool, slot_index);
            slot.readers++;
            node->pins[node->n_pins++] = {&pool, slot_index};
            slot_indices[index] = slot_index;
            dev.inserts++;
            dev.fills++;
            dev.hits++;
            hits++;
        } else if (slab_buf) {
            memcpy((char *)dev.staging.mapped +
                       (size_t)(fills_done - 1) * node->expert_size,
                   source, node->expert_size);
            pending.push_back({slot_index, index});
            // stays in 'copying' until the batch copy below succeeds
        }
    }

    // Batch-copy staged payloads into the device-local slab, then promote
    // the pending slots. On failure roll them back so a later node cannot
    // consume the stale entries as hits.
    if (!pending.empty() && !dev.host_mapped && slab_buf) {
        const bool copy_ok = vk_submit_and_wait(dev, [&](VkCommandBuffer cmd) {
            std::vector<VkBufferCopy> regions;
            regions.reserve(pending.size());
            for (size_t i = 0; i < pending.size(); i++) {
                VkBufferCopy region = {};
                region.srcOffset = (VkDeviceSize)i * node->expert_size;
                region.dstOffset = (VkDeviceSize)pending[i].slot * node->expert_size;
                region.size = node->expert_size;
                regions.push_back(region);
            }
            vkCmdCopyBuffer(cmd, dev.staging.buffer, slab_buf->buffer,
                            (uint32_t)regions.size(), regions.data());
            return true;
        });

        if (copy_ok) {
            for (const pending_fill & fill : pending) {
                moe_cache_slot & pslot = pool.slots[fill.slot];
                pslot.state = moe_cache_slot_state::valid;
                moe_cache_lru_push_back(pool, fill.slot);
                pslot.readers++;
                node->pins[node->n_pins++] = {&pool, fill.slot};
                slot_indices[fill.index] = fill.slot;
                dev.inserts++;
                dev.fills++;
                dev.hits++;
                hits++;
            }
        } else {
            // Roll back: erase map entry, free the slot, keep slot_indices
            // at -1 so the CPU path recomputes these rows. The slab contents
            // are unknown after a failed transfer; mark the device dead so no
            // later node can hit stale entries.
            for (const pending_fill & fill : pending) {
                moe_cache_slot_reset(pool, fill.slot, true);
                dev.fill_failures++;
            }
            dev.dead.store(true);
            MOE_CACHE_LOG("[moe-cache] Vulkan%d: staged fill transfer failed; "
                          "rolled back %zu fills and disabled the device cache\n",
                          dev.physical, pending.size());
        }
    }

    dev.nodes++;
    return hits;
}

// ---------------------------------------------------------------------------
// Dispatch: run the Vulkan matvec kernel over the hit rows.
// ---------------------------------------------------------------------------

static int vk_moe_dispatch(void * opaque, int wtype, int64_t n_in, int64_t n_out,
                           int n_hits, const int32_t * slot_indices,
                           const float * const * act_rows) {
    moe_cache_node * node = (moe_cache_node *)opaque;
    if (!node || !node->planned || !slot_indices || !act_rows ||
        n_hits <= 0 || n_hits > moe_cache_node_rows_max ||
        n_hits != node->n_pins ||
        wtype != node->wtype || n_in != node->n_in || n_out != node->n_out) {
        return 0;
    }

    moe_cache_vulkan_device & dev =
        static_cast<moe_cache_vulkan_device &>(*node->device);
    if (dev.dead.load() || moe_cache_fail(*node->session, "dispatch")) {
        std::lock_guard<std::mutex> lock(node->session->mu);
        dev.dispatch_failures++;
        return 0;
    }
    const size_t pool_index = (size_t)node->pool_index >= 0
        ? (size_t)node->pool_index : 0;
    if (dev.pool_buffers.empty() || pool_index >= dev.pool_buffers.size()) {
        return 0;
    }
    vk_buf & slab_buf = dev.pool_buffers[pool_index];

    const int64_t padded_n_in = ((n_in + QK8_1 - 1) / QK8_1) * QK8_1;
    const int64_t expert_stride = node->expert_size;
    const int64_t row_stride = ggml_row_size((ggml_type)wtype, n_in);

    const VkMemoryPropertyFlags host_props =
        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT;
    const VkMemoryPropertyFlags dev_props = dev.host_mapped
        ? (VkMemoryPropertyFlags)(VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT |
                                  VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                                  VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)
        : (VkMemoryPropertyFlags)VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT;
    VkBufferUsageFlags dev_usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
    if (!dev.host_mapped) {
        dev_usage |= VK_BUFFER_USAGE_TRANSFER_SRC_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT;
    }

    const VkDeviceSize ids_bytes = (VkDeviceSize)n_hits * sizeof(int32_t);
    const VkDeviceSize act_bytes = (VkDeviceSize)n_hits *
        (padded_n_in / QK8_1) * sizeof(block_q8_1);
    const VkDeviceSize out_bytes = (VkDeviceSize)n_hits * (VkDeviceSize)n_out * sizeof(float);

    if (!vk_buf_reserve(dev, dev.ids_buf, ids_bytes, dev_usage, dev_props) ||
        !vk_buf_reserve(dev, dev.act_buf, act_bytes, dev_usage, dev_props) ||
        !vk_buf_reserve(dev, dev.out_buf, out_bytes, dev_usage, dev_props) ||
        !vk_buf_reserve(dev, dev.params_buf, 6 * sizeof(int64_t),
                        VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT, host_props)) {
        return 0;
    }

    // select pipeline by weight type
    VkPipeline pipeline = dev.pipeline_q8_0;
    switch (wtype) {
        case GGML_TYPE_Q8_0: pipeline = dev.pipeline_q8_0; break;
        case GGML_TYPE_Q4_0: pipeline = dev.pipeline_q4_0; break;
        case GGML_TYPE_Q4_K: pipeline = dev.pipeline_q4_K; break;
        case GGML_TYPE_Q6_K: pipeline = dev.pipeline_q6_K; break;
        case GGML_TYPE_Q5_K: pipeline = dev.pipeline_q5_K; break;
        case GGML_TYPE_Q1_0: pipeline = dev.pipeline_q1_0; break;
        case GGML_TYPE_Q2_0: pipeline = dev.pipeline_q2_0; break;
        case GGML_TYPE_Q4_1: pipeline = dev.pipeline_q4_1; break;
        case GGML_TYPE_Q5_0: pipeline = dev.pipeline_q5_0; break;
        case GGML_TYPE_Q5_1: pipeline = dev.pipeline_q5_1; break;
        case GGML_TYPE_Q2_K: pipeline = dev.pipeline_q2_K; break;
        case GGML_TYPE_Q3_K: pipeline = dev.pipeline_q3_K; break;
        case GGML_TYPE_IQ2_XXS: pipeline = dev.pipeline_iq2_xxs; break;
        case GGML_TYPE_IQ2_XS: pipeline = dev.pipeline_iq2_xs; break;
        case GGML_TYPE_IQ2_S: pipeline = dev.pipeline_iq2_s; break;
        case GGML_TYPE_IQ3_XXS: pipeline = dev.pipeline_iq3_xxs; break;
        case GGML_TYPE_IQ3_S: pipeline = dev.pipeline_iq3_s; break;
        case GGML_TYPE_IQ1_S: pipeline = dev.pipeline_iq1_s; break;
        case GGML_TYPE_IQ1_M: pipeline = dev.pipeline_iq1_m; break;
        case GGML_TYPE_IQ4_NL: pipeline = dev.pipeline_iq4_nl; break;
        case GGML_TYPE_IQ4_XS: pipeline = dev.pipeline_iq4_xs; break;
        case GGML_TYPE_MXFP4: pipeline = dev.pipeline_mxfp4; break;
        case GGML_TYPE_NVFP4: pipeline = dev.pipeline_nvfp4; break;
        default: break;
    }
    if (!pipeline) {
        return 0;
    }

    // quantize activations into host scratch
    const size_t act_bytes_needed =
        (size_t)n_hits * (size_t)(padded_n_in / QK8_1) * sizeof(block_q8_1);
    if (act_bytes_needed > dev.h_act_cap_bytes) {
        try {
            dev.h_act.resize((act_bytes_needed + sizeof(float) - 1) / sizeof(float));
        } catch (...) {
            return 0;
        }
        dev.h_act_cap_bytes = act_bytes_needed;
    }
    block_q8_1 * act_q8 = (block_q8_1 *)dev.h_act.data();
    for (int i = 0; i < n_hits; i++) {
        vk_quantize_act_q8_1(act_rows[i], act_q8 + i * (padded_n_in / QK8_1),
                             n_in, padded_n_in);
    }

    // host-visible buffers are written directly; device-local buffers are
    // staged. Staging layout: [0, ids) ids, [ids, ids+act) acts,
    // [ids+act, ids+act+out) results. The result region is disjoint from
    // the upload regions, so no same-buffer hazard exists within the
    // dispatch command buffer.
    const VkDeviceSize out_stage_offset = ids_bytes + act_bytes;
    if (dev.host_mapped) {
        memcpy(dev.ids_buf.mapped, slot_indices, ids_bytes);
        memcpy(dev.act_buf.mapped, act_q8, act_bytes);
    } else {
        const VkDeviceSize stage_need = ids_bytes + act_bytes + out_bytes;
        if (!vk_buf_reserve(dev, dev.staging, stage_need,
                            VK_BUFFER_USAGE_TRANSFER_SRC_BIT |
                            VK_BUFFER_USAGE_TRANSFER_DST_BIT,
                            host_props)) {
            return 0;
        }
        memcpy(dev.staging.mapped, slot_indices, ids_bytes);
        memcpy((char *)dev.staging.mapped + ids_bytes, act_q8, act_bytes);
    }

    // params (host-visible, written before submit -> visible after submit)
    int64_t params[6] = {n_in, n_out, expert_stride, row_stride, n_hits, padded_n_in};
    memcpy(dev.params_buf.mapped, params, sizeof(params));

    // update descriptor set for this node
    VkDescriptorBufferInfo slab_info = {slab_buf.buffer, 0, VK_WHOLE_SIZE};
    VkDescriptorBufferInfo ids_info  = {dev.ids_buf.buffer, 0, VK_WHOLE_SIZE};
    VkDescriptorBufferInfo act_info  = {dev.act_buf.buffer, 0, VK_WHOLE_SIZE};
    VkDescriptorBufferInfo out_info  = {dev.out_buf.buffer, 0, VK_WHOLE_SIZE};
    VkDescriptorBufferInfo params_info = {dev.params_buf.buffer, 0, 6 * sizeof(int64_t)};

    VkWriteDescriptorSet writes[5] = {};
    for (int i = 0; i < 4; i++) {
        writes[i].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        writes[i].dstSet = dev.ds;
        writes[i].dstBinding = i;
        writes[i].descriptorCount = 1;
        writes[i].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    }
    writes[0].pBufferInfo = &slab_info;
    writes[1].pBufferInfo = &ids_info;
    writes[2].pBufferInfo = &act_info;
    writes[3].pBufferInfo = &out_info;
    writes[4].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
    writes[4].dstSet = dev.ds;
    writes[4].dstBinding = 4;
    writes[4].descriptorCount = 1;
    writes[4].descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
    writes[4].pBufferInfo = &params_info;
    vkUpdateDescriptorSets(dev.vk_device, 5, writes, 0, nullptr);

    const uint32_t total_threads = (uint32_t)n_hits * (uint32_t)n_out;
    const uint32_t n_groups = (total_threads + 255) / 256;

    const bool ok = vk_submit_and_wait(dev, [&](VkCommandBuffer cmd) {
        if (!dev.host_mapped) {
            VkBufferCopy ids_region = {};
            ids_region.size = ids_bytes;
            vkCmdCopyBuffer(cmd, dev.staging.buffer, dev.ids_buf.buffer, 1, &ids_region);

            VkBufferCopy act_region = {};
            act_region.srcOffset = ids_bytes;
            act_region.size = act_bytes;
            vkCmdCopyBuffer(cmd, dev.staging.buffer, dev.act_buf.buffer, 1, &act_region);

            VkBufferMemoryBarrier copy_barrier = {};
            copy_barrier.sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER;
            copy_barrier.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
            copy_barrier.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
            copy_barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
            copy_barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
            VkBufferMemoryBarrier copy_barriers[2] = {copy_barrier, copy_barrier};
            copy_barriers[0].buffer = dev.ids_buf.buffer;
            copy_barriers[0].size = VK_WHOLE_SIZE;
            copy_barriers[1].buffer = dev.act_buf.buffer;
            copy_barriers[1].size = VK_WHOLE_SIZE;
            vkCmdPipelineBarrier(cmd,
                    VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                    0, 0, nullptr, 2, copy_barriers, 0, nullptr);
        }

        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline);
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE,
                                dev.pipeline_layout, 0, 1, &dev.ds, 0, nullptr);
        vkCmdDispatch(cmd, n_groups, 1, 1);

        if (!dev.host_mapped) {
            VkBufferMemoryBarrier out_barrier = {};
            out_barrier.sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER;
            out_barrier.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
            out_barrier.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
            out_barrier.buffer = dev.out_buf.buffer;
            out_barrier.size = VK_WHOLE_SIZE;
            out_barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
            out_barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
            vkCmdPipelineBarrier(cmd,
                    VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
                    0, 0, nullptr, 1, &out_barrier, 0, nullptr);

            VkBufferCopy out_region = {};
            out_region.dstOffset = out_stage_offset;
            out_region.size = out_bytes;
            vkCmdCopyBuffer(cmd, dev.out_buf.buffer, dev.staging.buffer, 1, &out_region);
        }
        return true;
    });

    if (!ok) {
        dev.dispatch_failures++;
        return 0;
    }
    node->dispatched = true;
    return 1;
}

// ---------------------------------------------------------------------------
// Collect: copy results into dst_rows.
// ---------------------------------------------------------------------------

static int vk_moe_collect(void * opaque, int n_hits, float * const * dst_rows,
                          int64_t n_out) {
    moe_cache_node * node = (moe_cache_node *)opaque;
    if (!node || !node->dispatched || n_hits <= 0 ||
        n_hits > moe_cache_node_rows_max ||
        node->n_pins != n_hits || !dst_rows || n_out != node->n_out) {
        return 0;
    }
    for (int index = 0; index < n_hits; index++) {
        if (!dst_rows[index]) {
            return 0;
        }
    }

    moe_cache_vulkan_device & dev =
        static_cast<moe_cache_vulkan_device &>(*node->device);
    moe_cache_session & session = *node->session;
    bool ok = !dev.dead.load() && !moe_cache_fail(session, "collect");
    if (ok) {
        const size_t out_bytes = (size_t)n_hits * (size_t)n_out * sizeof(float);
        if (dev.host_mapped) {
            // results already in the host-visible out buffer
            const float * out = (const float *)dev.out_buf.mapped;
            for (int index = 0; index < n_hits; index++) {
                memcpy(dst_rows[index], out + (size_t)index * n_out,
                       (size_t)n_out * sizeof(float));
            }
        } else {
            // copy-back already landed in staging during dispatch
            if (dev.staging.size < out_bytes || !dev.staging.mapped) {
                ok = false;
            } else {
                const size_t padded_n_in =
                    ((size_t)node->n_in + QK8_1 - 1) / QK8_1 * QK8_1;
                const size_t act_bytes =
                    (size_t)node->n_pins * (padded_n_in / QK8_1) * sizeof(block_q8_1);
                const size_t out_stage_offset =
                    (size_t)node->n_pins * sizeof(int32_t) + act_bytes;
                const float * out = (const float *)dev.staging.mapped + out_stage_offset / sizeof(float);
                for (int index = 0; index < n_hits; index++) {
                    memcpy(dst_rows[index], out + (size_t)index * n_out,
                           (size_t)n_out * sizeof(float));
                }
            }
        }
    }
    node->dispatched = false;
    {
        std::lock_guard<std::mutex> lock(session.mu);
        if (!ok) {
            dev.collect_failures++;
        }
        dev.collect_calls++;
        if (session.config.stats_every > 0 &&
            dev.collect_calls % session.config.stats_every == 0) {
            vk_moe_log_stats(dev);
        }
    }
    return ok ? 1 : 0;
}

// ---------------------------------------------------------------------------
// End: release slot pins and the node.
// ---------------------------------------------------------------------------

static void vk_moe_end(void * opaque) {
    std::unique_ptr<moe_cache_node> node((moe_cache_node *)opaque);
    if (!node) {
        return;
    }
    moe_cache_session & session = *node->session;
    {
        std::lock_guard<std::mutex> lock(session.mu);
        for (int index = 0; index < node->n_pins; index++) {
            const moe_cache_pin & pin = node->pins[index];
            if (pin.pool && pin.slot >= 0 && pin.slot < pin.pool->n_slots) {
                moe_cache_slot & slot = pin.pool->slots[pin.slot];
                if (slot.readers > 0) {
                    slot.readers--;
                }
            }
        }
        session.active_nodes--;
        session.idle_cv.notify_all();
    }
}

// ---------------------------------------------------------------------------
// Fused SwiGLU — not implemented for v1; stock CPU path handles the node.
// ---------------------------------------------------------------------------

static void * vk_moe_fused_begin(const ggml_moe_cache_tensor_desc * up,
                                 const ggml_moe_cache_tensor_desc * gate,
                                 int glu_op, float up_min, float up_max,
                                 float gate_min, float gate_max,
                                 const int32_t * ids, int n_rows,
                                 int64_t n_tokens,
                                 const float * const * act_rows,
                                 uint64_t * hit_mask) {
    (void)up; (void)gate; (void)glu_op;
    (void)up_min; (void)up_max; (void)gate_min; (void)gate_max;
    (void)ids; (void)n_rows; (void)n_tokens; (void)act_rows; (void)hit_mask;
    return nullptr;
}

// ---------------------------------------------------------------------------
// Invalidate: drop cached slots whose tensor range overlaps [base, base+size).
// ---------------------------------------------------------------------------

static void vk_moe_invalidate(const void * base, size_t size) {
    if (!base || size == 0) {
        return;
    }
    if (g_session_count.load(std::memory_order_acquire) == 0) {
        return;
    }
    std::lock_guard<std::mutex> registry_lock(g_registry_mu);
    for (moe_cache_session * session : g_sessions) {
        std::lock_guard<std::mutex> lock(session->mu);
        for (auto & dev_ptr : session->devices) {
            for (auto & pool_ptr : dev_ptr->pools) {
                for (int i = 0; i < pool_ptr->n_slots; i++) {
                    if (pool_ptr->slots[i].key.tensor &&
                        moe_cache_ranges_overlap(
                            pool_ptr->slots[i].key.tensor,
                            pool_ptr->expert_size, base, size)) {
                        moe_cache_slot_reset(*pool_ptr, i, true);
                    }
                }
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

// Each backend wires its own function table into the provider registry
// (ggml-backend-moe-cache.h). The owner is the backend reg pointer so that
// query_device can match ggml_backend_dev_backend_reg(device).

static void vk_moe_register(const void * owner) {
    g_moe_cache_owner = owner;
    ggml_moe_cache_api api = {};
    api.owner = owner;
    api.query_config = vk_moe_query_config;
    api.query_device = vk_moe_query_device;
    api.query_shape = vk_moe_query_shape;
    api.session_create = vk_moe_session_create;
    api.session_destroy = vk_moe_session_destroy;
    api.session_enter = vk_moe_session_enter;
    api.session_leave = vk_moe_session_leave;
    api.begin = vk_moe_begin;
    api.plan = vk_moe_plan;
    api.dispatch = vk_moe_dispatch;
    api.collect = vk_moe_collect;
    api.end = vk_moe_end;
    api.fused_begin = vk_moe_fused_begin;
    api.invalidate = vk_moe_invalidate;
    ggml_moe_cache_register(&api);
}

// Prior declaration so the definition below does not trip -Wmissing-declarations.
extern "C" void ggml_vulkan_moe_cache_register(void * reg);

extern "C" void ggml_vulkan_moe_cache_register(void * reg) {
    vk_moe_register(reg);
}
